### ISSUE TITLE
Update instructions for 4.0 release

### ISSUE THREAD

**Issue by becw** [palantirnet/the-build#186]
There are some major changes in 4.x and we need update steps for our existing projects, even if it's "remove the previous version and install the new one, manually applying customizations".

**Comment by byrond** [comment]
We need to consider the version of the skeleton that was used to create a given project. Older versions may not have all the right `settings.*.php` files and `include` statements in `settings.php` that will be required once `settings.build.php` is no longer being created/managed by the-build.
