### ISSUE TITLE
Add instructions to add SSH key to platform account and CircleCI

### ISSUE THREAD

**Issue by byrond** [palantirnet/the-build#203]
The deployment examples for Pantheon and Acquia need instructions for creating a new account on the platform used, a new SSH key, and adding this key to the account and CircleCI project settings.

https://github.com/palantirnet/the-build/blob/0e544533e85afc8155bd1cc5b689209ec954e2d6/defaults/install/.circleci/deploy-pantheon.example#L1

**Comment by byrond** [comment]
Created a Jira story for this issue in an internal project.

**Comment by becw** [comment]
@byrond similar to this? https://palantir.atlassian.net/wiki/spaces/PLAYB/pages/1237745669/Automating+deployment+from+CircleCI+to+Pantheon
