### ISSUE TITLE
Allow for local db installs

### ISSUE THREAD

**Issue by lukewertz** [palantirnet/the-build#31]
Several projects have had to script a way to allow local db installs that are not:
1) "clean" installs (i.e.: an empty database)
2) a "pulled db" (i.e.: a canonical from Acquia)

We should script the build in such a way that it can consistently build from a specified database dump.

See [here](https://github.com/massgov/mass/pull/180/files) and [here](https://github.com/palantirnet/academyhealth/blob/develop/build.xml#L60) for some examples of how to do this.

**Comment by becw** [comment]
We have the `drupal-load-db` task now.
