### ISSUE TITLE
Need to validate that artifact repository remote matches configuration

### ISSUE THREAD

**Issue by becw** [palantirnet/the-build#32]
The acquia git repo used by the deploy tasks doesn't necessarily use the same repo source/origin as the build properties... so if you change the repo source in the build properties but don't blow away the repo, then you keep pushing to the old repo source.

**Comment by becw** [comment]
This is currently still an issue with the release-2.0 artifact builds -- the `artifact-initializeRepository` target doesn't validate that the repo remote is the same as the remote that is configured.

**Comment by byrond** [comment]
Using the current `release-2.0` branch, I changed the `artifact.git.remote` and attempted to run `phing artifact`.  I received the following, which suggests this is being validated:
```
example > artifact-safeToBuild:

     [echo] Deploy environment:   other
     [echo] Repository status:    clean
     [echo] Artifact repository:  artifacts/build has wrong remote configuration
     [echo]   * Directory 'artifacts/build' exists but the 'origin' remote is not /home/vagrant/remotetest. Please move or delete before continuing.
     [echo] Destination branch:   artifact-master
     [echo] 
```

It looks like that is happening here:
https://github.com/palantirnet/the-build/blob/81c75a4964935da23e44efe2571d25c363036722/tasks/artifact.xml#L119-L127

**Comment by becw** [comment]
Ah, oops, I verified this as well in another issue! We've covered all the bases on this though so I'm happy :)
