### ISSUE TITLE
Commits should be properly attributed

### ISSUE THREAD

**Issue by lukewertz** [palantirnet/the-build#66]
When troubleshooting deployment issues, it'd be useful to see who made deployments. For example, troubleshooting things on the Acquia build branch shows the following history for the mass.gov project:

```
commit 3ea479e4202d6f753dd3a3c5118f9069de860b83
Author: vagrant <vagrant@mass.local>
Date:   Thu Mar 2 22:28:09 2017 +0000

    [0.14.0] Drupal artifact.

commit 6a0cbf1056d97ff7425f76f71530b5ebc1a678dc
Author: vagrant <vagrant@mass.local>
Date:   Thu Mar 2 21:55:53 2017 +0000

    [0.14.0-rc3] Drupal artifact.

commit 959472cdc9746b1b4423681b0cc6d47974b34a98
Author: vagrant <vagrant@mass.local>
Date:   Thu Mar 2 21:44:41 2017 +0000

    [0.14.0-rc2] Drupal artifact.

commit 2c87dae5eb84da33237e717e4fd530b534aa9b94
Author: vagrant <vagrant@mass.local>
Date:   Thu Mar 2 21:38:07 2017 +0000

    [0.14.0-rc2] Drupal artifact.

commit 82b3b2110c741c44bb9aa31c064dbfc66562a44e
Author: vagrant <vagrant@mass.local>
Date:   Thu Mar 2 20:36:14 2017 +0000

    [0.14.0-rc1] Drupal artifact.

commit 335dce826b48209e71770d713bd0499c73225344
Author: vagrant <vagrant@mass.local>
Date:   Tue Feb 28 19:36:14 2017 +0000
```

It'd be nice to know who made each of those commits since it is detached from the repo history.

**Comment by becw** [comment]
I think we could do this by adding a bit to [the-vagrant](https://github.com/palantirnet/the-vagrant) provisioning where we set up the git user within the VM based on how it is on the user's localhost. I've created [the-vagrant #57](https://github.com/palantirnet/the-vagrant/issues/57) over there to address this.

**Comment by becw** [comment]
This is now solved in the-vagrant by https://github.com/palantirnet/the-vagrant/issues/57!
