### ISSUE TITLE
Consider reintegrating artifacts into the repo?

### ISSUE THREAD

**Issue by becw** [palantirnet/the-build#72]
Steps:

* update docroot to match host's needs
* wrap hosting components into the repo - config stuff mostly
* either don't or do check in composer dependencies
* when composer dependencies are checked in:
  * when the commit contains changes to composer.json or composer.lock
  * any changes in the vendor directory and drupal modules/themes/profiles should be checked in, maybe
  * run `composer validate` and if it returns false then fail
  * run `composer install --dry-run` and look for "Nothing to install or update"
* symlink between the prototype and the theme
  * when there are changes to the sass, make sure that css is regenerated?
* provide a default settings.php that does the environment switching
* ignore other settings.*.php files
* exclude .htaccess file from scaffolding after initializing

* should we do a setup script based on the skeleton?
* reintegrating with current artifacts

**Comment by patrickfweston** [comment]
#79 would allow for easier symlinking between the prototype and the theme with an integrated artifact

**Comment by becw** [comment]
Artifact builds are refactored in 2.0.
