### ISSUE TITLE
Upgrade to Phing 2.16.0

### ISSUE THREAD

**Issue by patrickfweston** [palantirnet/the-build#79]
The newest version of Phing allows for relative symlinks. This can be beneficial when creating an integrated deployment artifact as it would allow us to use our existing symlinks on the hosting environment.

Currently, attempting to create relative symbolic links with our `includeresource` task or the default `symlink` task throws errors.

Release: https://github.com/phingofficial/phing/releases/tag/2.16.0

**Comment by becw** [comment]
You should be able to update your project to Phing 2.16, since `the-build` requires `^2.14`, which should match any version until `3.0`.

Try `composer update phing/phing --with-dependencies`...

**Comment by patrickfweston** [comment]
Good to know! I'll do that. Thanks!

**Comment by patrickfweston** [comment]
Ah, looks like phing needs a 3.x version of Symfony YAML while other packages require <3.0.
