### ISSUE TITLE
Required package(s) missing

### ISSUE THREAD

**Issue by lukewertz** [palantirnet/the-build#81]
In order for code sniffing to work, PHP_CS needs to be available on the machine that's running the job. I recommend we require `quizlabs/php_codesniffer:2.*` as part of this project so the necessary package is installed.

**Comment by becw** [comment]
We can add this as required. What happened is that the latest version of `drupal/coder` relies on this library but no longer declares a dependency to composer :(

**Comment by becw** [comment]
Coder is requiring this properly again now.
